import { createFileRoute } from "@tanstack/react-router";
import { alerts } from "../lib/dummyData";

export const Route = createFileRoute("/alerts")({
  head: () => ({ meta: [{ title: "Alerts – PdM Edge AI" }] }),
  component: Alerts,
});

const typeStyles: Record<string, { label: string; cls: string }> = {
  Critical: { label: "Critical Failure Risk", cls: "border-l-danger bg-danger/5" },
  Vibration: { label: "High Vibration", cls: "border-l-warning bg-warning/5" },
  Temperature: { label: "High Temperature", cls: "border-l-warning bg-warning/5" },
  Maintenance: { label: "Maintenance Required", cls: "border-l-primary bg-primary/5" },
};

function Alerts() {
  return (
    <div>
      <h2 className="text-2xl font-bold mb-1">Alerts</h2>
      <p className="text-muted-foreground mb-6">Recent alerts generated by the Edge AI model.</p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {alerts.map((a) => {
          const s = typeStyles[a.type];
          return (
            <div key={a.id} className={`bg-card border border-border border-l-4 rounded-lg p-4 ${s.cls}`}>
              <div className="flex justify-between items-start mb-1">
                <h3 className="font-semibold">{s.label}</h3>
                <span className="text-xs text-muted-foreground">{a.time}</span>
              </div>
              <p className="text-sm text-muted-foreground mb-2">Machine: <strong className="text-foreground">{a.machineId}</strong></p>
              <p className="text-sm">{a.message}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
